#! /usr/bin/python

import re
import random

def repl_fun(match):
    return str(random.randint(0,9))

sentence = input("Enter your sentence: ")

for i in range(len(sentence)):
    code=str(chr(ord(sentence[i]) + 1))
    replaced = re.sub("!", repl_fun, code)
    replaced1 = re.sub("{", repl_fun, replaced)
    print (replaced1, end=" ")








